---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://grafana.github.io/loki/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: loki
      version: 2.1.2
  install:
    createNamespace: true
  interval: 10m0s
  targetNamespace: loki-stack

