---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nats
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://nats-io.github.io/k8s/helm/charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
      version: 0.9.2
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: my-nats
  targetNamespace: nats

