---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: project-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/Smuliii/devopswithkubernetes

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: project-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./part4/project-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: project-app
  targetNamespace: dwk-project-app
  decryption:
    provider: sops
    secretRef:
      name: sops-pgp

